<script>
    function getDataWithCallBack(fnSuccess,fnError){
        var d = Math.floor(Math.random() * 100)
        if(d >= 50)
            fnSuccess({data:d})
        else
            fnError({ errMsg: "Error: " + d + " is less than 50"})
    }

    getDataWithCallBack(fnSuccess,fnError);

    function fnSuccess(obj){
        console.log("Data is " + obj.data)
    }

    function fnError(obj){
        console.log("Error message is " + obj.errMsg)
    }

    console.log("End of script")
</script>